version: 2
jobs:
  danger:
    working_directory: ~/workspace
    docker:
      - image: node:8

    environment:

    timezone:
      Asia/Tokyo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            yarn
      - run:
          name: yarn run danger
          command: |
            yarn danger ci

workflows:
  version: 2
  danger:
    jobs:
      - danger